<center>
    <img src="https://drive.google.com/uc?export=view&id=1hDKusF04c0lNZA_qOShvWQrpImayVKz8"  width="1000" />
</center>


# Pertemuan 10 
# Pembangunan Model : Decision Tree

# About Iris dataset
![](https://www.oreilly.com/library/view/python-artificial-intelligence/9781789539462/assets/462dc4fa-fd62-4539-8599-ac80a441382c.png)


The iris dataset contains the following data **(Before Cleansing)**
* 50 samples of 3 different species of iris (150 samples total)
* Measurements: sepal length, sepal width, petal length, petal width
* The format for the data: (sepal length, sepal width, petal length, petal width)

### The variables are:
![](https://i.imgur.com/PQqYGaW.png)
* sepal_length: Sepal length, dalam Centimeter(Cm),sebagai <b>Input</b>.
* sepal_width: Sepal width, dalam Centimeter(Cm), sebagai <b>Input</b>.
* petal_length: Petal length, dalam Centimeter(Cm), sebagai <b>Input</b>.
* petal_width: Petal width, dalam Centimeter(Cm), sebagai <b>Input</b>.
* class: Iris Setosa, Versicolor, or Virginica, sebagai <b>Target</b>.

# Latihan (1)

### Melakukan import library yang dibutuhkan

In [ ]:
# import library pandas
<...>

# Import library numpy
<...>

# Import library matplotlib dan seaborn untuk visualisasi
<...>
<...>

# me-non aktifkan peringatan pada python
import warnings 
warnings.filterwarnings('ignore')

Kode dibawah tidak perlu dijalankan apabila sudah mempunyai file <b>'Iris_AfterClean.csv'</b>

In [ ]:
#Download dataset
!gdown 1-F8Aex060zVihmPI9DvoJo5AmUtomXCL

Downloading...
From: https://drive.google.com/uc?id=1-F8Aex060zVihmPI9DvoJo5AmUtomXCL
To: /content/Iris_AfterClean.csv
100% 4.47k/4.47k [00:00<00:00, 5.35MB/s]


### Load Dataset

In [ ]:
#Panggil file (load file bernama Iris_AfterClean.csv) dan simpan dalam dataframe
# Sesuaikan lokasi PATH dari dataset
iris = pd.read_csv('/content/Iris_AfterClean.csv')

# Latihan (2)
Tampilkan 10 data teratas dari dataset <b> Iris </b>

In [ ]:
# tampilkan 10 baris data teratas
# <...>

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            4.6           3.1            1.5           0.2  Iris-setosa
1            5.0           3.6            1.4           0.2  Iris-setosa
2            5.4           3.9            1.7           0.4  Iris-setosa
3            4.9           3.1            1.5           0.1  Iris-setosa
4            5.4           3.7            1.5           0.2  Iris-setosa

# Latihan (3)
Tampilkan 5 data terbawah dari dataset <b> Iris</b>

In [ ]:
# 5 data terbawah
# <...>

# Latihan (4)
Definisikan variable X dengan kolom Input = <code>SepalLengthCm, SepalWidthCm,	PetalLengthCm,	PetalWidthCm</code>

Definisikan variable Y dengan kolom target = <code>Species</code>

In [ ]:
X=iris.iloc[<...>].values
y=iris.iloc[<...>].values

## Label encoding
![](https://miro.medium.com/max/772/1*QQe-4476Oy3_dI1vhb3dDg.png)


Seperti yang kita lihat, label bersifat kategoris. KNeighborsClassifier tidak menerima label string. Kita perlu menggunakan LabelEncoder untuk mengubahnya menjadi angka. Iris-setosa sesuai dengan 0, Iris-versicolor sesuai dengan 1 dan Iris-virginica sesuai dengan 2.



### Transformasi label data species dengan menggunakan library LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# 3. Building Machine Learning Models

### Import library dalam kebutuhan membangun model 

In [ ]:
#Metrics
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report

# Import Library Confussion Matrix
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

#Model Select
from sklearn.model_selection import KFold,train_test_split,cross_val_score

# Import Library Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

from sklearn.model_selection import train_test_split

from sklearn import linear_model


### Splitting The Data into Training And Testing Dataset
![](https://data-flair.training/blogs/wp-content/uploads/sites/2/2018/08/1-16.png)

Train/test split adalah salah satu metode yang dapat digunakan untuk mengevaluasi performa model machine learning. Metode evaluasi model ini membagi dataset menjadi dua bagian yakni bagian yang digunakan untuk training data dan untuk testing data dengan proporsi tertentu. Train data digunakan untuk fit model machine learning, sedangkan test data digunakan untuk mengevaluasi hasil fit model tersebut.

![image.png](attachment:image.png)


Python memiliki library yang dapat mengimplementasikan train/test split dengan mudah yaitu Scikit-Learn. Untuk menggunakannya, kita perlu mengimport Scikit-Learn terlebih dahulu, kemudian setelah itu kita dapat menggunakan fungsi train_test_split().

# Latihan (5)

### split data train dan test dengan function train_test_split() dengan train_size= 70%, test_size= 30% dan random_state=0

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=<...>,random_state=<...>)

Sekarang kita akan melatih beberapa model Machine Learning dan membandingkan hasilnya. Perhatikan bahwa karena set data tidak memberikan label untuk set pengujiannya, kita perlu menggunakan prediksi pada set pelatihan untuk membandingkan algoritme satu sama lain.

### 3.1 Decision Tree:

decision tree adalah struktur seperti diagram alur di mana setiap simpul internal mewakili pengujian pada fitur (misalnya apakah flip koin muncul kepala atau ekor), setiap simpul daun mewakili label kelas (keputusan diambil setelah menghitung semua fitur) dan cabang mewakili konjungsi fitur yang mengarah ke label kelas tersebut. Jalur dari akar ke daun mewakili aturan klasifikasi.

![](https://miro.medium.com/max/1000/1*LMoJmXCsQlciGTEyoSN39g.jpeg)



### Bangun model DecisionTreeClassifier dan akurasi nya

In [ ]:
decision_tree=tree.DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)  
Y_pred = decision_tree.predict(X_test) 
accuracy_dt=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_decision_tree = round(decision_tree.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for DecisionTree\n',cm)
print('accuracy_DecisionTree: %.3f' %accuracy)
print('precision_DecisionTree: %.3f' %precision)
print('recall_DecisionTree: %.3f' %recall)
print('f1-score_DecisionTree : %.3f' %f1)

Confusion matrix for DecisionTree
 [[12  0  0]
 [ 0 12  3]
 [ 0  2 13]]
accuracy_DecisionTree: 0.881
precision_DecisionTree: 0.881
recall_DecisionTree: 0.881
f1-score_DecisionTree : 0.881


In [ ]:
df_merge = pd.DataFrame({'Actual': y_test, 'Predicted': Y_pred})
print(df_merge)

    Actual  Predicted
0        1          1
1        1          1
2        0          0
3        1          1
4        2          2
5        0          0
6        2          2
7        2          2
8        2          2
9        0          0
10       2          2
11       0          0
12       1          1
13       1          1
14       2          1
15       2          2
16       2          2
17       2          2
18       0          0
19       2          2
20       2          2
21       0          0
22       2          2
23       0          0
24       0          0
25       1          1
26       0          0
27       1          1
28       0          0
29       0          0
30       1          1
31       1          1
32       2          1
33       1          2
34       2          2
35       1          2
36       1          2
37       2          2
38       1          1
39       1          1
40       1          1
41       0          0
